### PR TITLE
Storage branch: support for saving/loading last used directory & tags; handled IOException when saving a tasklist

### PR DESCRIPTION
**Pull request by dq-dx**
- Storage support for remembering last used directory
- Storage support for saving/loading HashMap<String, Integer> for the user tags
- Removed Serializable from Task and TimeConverter (not needed for Storage any more)
- Genericized private write/read methods to support writing/reading arbitrary
objects
- Changed default directory to ./Taskey savefiles

Implemented classes to handle IOException when saving a task list (untested):
- Added History.java
- Added FilenameEnum.java
- Added StorageException.java
- Storage.java: saveTaskList method now throws StorageException

### CODE REVIEW

**Comment by Nattaro13** [comment]
@dq-dx i'll merge this later. cos i also added a storage for the UserTagDatabase... whoops. I'll think of what to remove later.

**Comment by dq-dx** [comment]
@Nattaro13 I think it's a bit weird if the UserTagDatabase handles the saving and loading of itself though. Kinda like what Henry Chia meant in his example a few weeks ago that a Command object shouldn't contain the execute methods.

My saveTags and loadTags methods saves the whole UserTagDatabase object though. Whereas I see that your methods save the HashMap field. Which do u prefer?

**Comment by Nattaro13** [comment]
@dq-dx okay hmm that's fine then. i can remove my load and save. i think make it load and save by hashmap? Will be easier and less confusing. 
cos i will need to use it as well, (as well as Hubert). so i think i should make it handle the initialisation .
also, can you change the base directories of where the savefiles are stored? it's quite difficult to navigate to the bin files. maybe store all the base locations at /taskey/savefiles or something. thanks!

**Comment by dq-dx** [comment]
@Nattaro13 OK, I've made the requested changes.
- The saveTags and loadTags methods now accepts and returns a HashMap, respectively.
- The default storage directory has been changed to "\Taskey savefiles" (instead of just "\savefiles", so it should be clearer to the end-user what this folder is for).
- Added the relevant files to .gitignore

**Comment by Nattaro13** [comment]
@dq-dx alright thanks! :D
i'll fix the conflicts tmr before i push to master

**Pull request merged**
